// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByZitadelID = `-- name: GetUserByZitadelID :one
SELECT id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE zitadel_user_id = $1
`

func (q *Queries) GetUserByZitadelID(ctx context.Context, zitadelUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByZitadelID, zitadelUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username       = COALESCE(NULLIF($2, ''), username),
    email          = COALESCE(NULLIF($3, ''), email),
    email_verified = $4,
    phone          = $5,
    avatar_url     = $6
WHERE id = $1
RETURNING id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	ID            pgtype.UUID
	Column2       interface{}
	Column3       interface{}
	EmailVerified bool
	Phone         pgtype.Text
	AvatarUrl     pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.EmailVerified,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (zitadel_user_id, username, email, email_verified, phone, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (zitadel_user_id) DO UPDATE
    SET username       = EXCLUDED.username,
        email          = EXCLUDED.email,
        email_verified = EXCLUDED.email_verified,
        phone          = EXCLUDED.phone,
        avatar_url     = EXCLUDED.avatar_url
RETURNING id, zitadel_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at
`

type UpsertUserParams struct {
	ZitadelUserID string
	Username      string
	Email         string
	EmailVerified bool
	Phone         pgtype.Text
	AvatarUrl     pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ZitadelUserID,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
