FROM golang:1.26.1-alpine
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /app
COPY go.work go.work.sum ./
COPY api/go.mod api/go.sum ./api/
COPY worker/go.mod worker/go.su[m] ./worker/
COPY shared/go/go.mod shared/go/go.sum ./shared/go/
RUN go work sync
COPY . .
WORKDIR /app/api
CMD ["air"]
